basic_bitwise: basic_bitwise.c
	gcc basic_bitwise.c -o bin/basicme -Wall -Werror -g

elementary_bitwise: elementary_bitwise.c
	gcc elementary_bitwise.c -o bin/elementaryme -Wall -Werror -g

operators_bitwise: operators_bitwise.c
	gcc operators_bitwise.c -o bin/operateme -Wall -Werror -g

fields_bitfields: fields_bitfields.c
	gcc fields_bitfields.c -o bin/fieldme -Wall -Werror -g

shifty_bits: shifty_bits.c
	gcc shifty_bits.c -o bin/shiftyme -Wall -Werror -g -lm

packer: packer.c
	gcc packer.c -o bin/packme -Wall -Werror -g 
